# Type stubs for _mujoco_camrender (C++ pybind11 module)
# Generated manually — for IDE autocomplete support

from __future__ import annotations
from typing import Tuple, List, Optional, Dict
import numpy as np

class RenderMode:
    RGB: RenderMode
    Depth: RenderMode
    All: RenderMode

class RenderBackend:
    OpenGL: RenderBackend
    Filament: RenderBackend

class CameraParams:
    name: str
    width: int
    height: int
    fov: float
    orthographic: bool
    near_clip: float
    far_clip: float
    position: Tuple[float, float, float]
    lookat: Tuple[float, float, float]

class GLRenderer:
    def initialize(self, model_ptr: int, data_ptr: int) -> None: ...
    def update_scene(self, data_ptr: int) -> None: ...
    def render(self, camera_id: int, mode: RenderMode = ...) -> Dict[str, any]: ...
    def camera_count(self) -> int: ...
    def set_camera_params(self, cam_id: int, params: CameraParams) -> None: ...
    def reset_camera_params(self, cam_id: int) -> None: ...

class RenderPool:
    def __init__(self, num_threads: int, backend: RenderBackend = ...) -> None: ...
    def initialize(self, model_ptr: int, data_ptr: int) -> None: ...
    def render_all(self, camera_ids: List[int], mode: RenderMode = ...) -> List[Dict[str, any]]: ...
    def update_scene(self, data_ptr: int) -> None: ...
    def set_camera_params(self, cam_id: int, params: CameraParams) -> None: ...
    def thread_count(self) -> int: ...

class AsyncEngine:
    def start(self, model_ptr: int, data_ptr: int, framerate: float = ..., backend: RenderBackend = ..., num_threads: int = ...) -> None: ...
    def stop(self) -> None: ...
    def step_simulation(self) -> None: ...
    def get_latest_frame(self, camera_id: int) -> Optional[Dict[str, any]]: ...
    def set_camera_params(self, cam_id: int, params: CameraParams) -> None: ...
    def running(self) -> bool: ...
    def frame_count(self) -> int: ...
